// <auto-generated />
namespace Itad2015.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class workshopguestworkshop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workshopguestworkshop));
        
        string IMigrationMetadata.Id
        {
            get { return "201509291705099_workshopguest-workshop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
